default_language_version:
    python: python3.7
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: check-executables-have-shebangs
    - id: check-yaml
-   repo: https://github.com/mattlqx/pre-commit-ruby
    rev: v1.2.6
    hooks:
    - id: rubocop
      name: Check Ruby style with rubocop
      description: Enforce Ruby style guide with rubocop
      entry: bin/rubocop-wrapper.sh
      language: script
      types: ['ruby']
      stages: [commit]
      verbose: true
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.13.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
